# Site settings
title: TEDxYouth@WSHS
email: wshstededclub@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  tedxyouthwshs
baseurl: ""
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: SpartanTEDEd

# Build settings
markdown: kramdown
permalink: pretty

collections:
  team_members:
  speakers2017:
    output: true
  speakers2016:
    output: true
  community:
    output: true
